language: python
python:
  - "2.7"
  - "3.5"

#
# Installs PostgreSQL.
#
addons:
  postgresql: "9.4"

services:
  - postgresql
  - redis-server

#
# Creates PostgreSQL database.
#
before_script:
  - psql --command "CREATE USER metabase WITH SUPERUSER PASSWORD 'metabase';"
  - createdb -O metabase metabase

#
# Command to install dependencies.
#
install:
  - make setup

#
# Run tests + coverage.
#
script:
  - make test

#
# Send coverage report to coveralls.io
#
after_success:
  - coveralls

notifications:
    email: false
